events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    # Minimal logging
    access_log off;
    error_log /var/log/nginx/error.log crit;

    server {
        listen 8097;

        location / {
            proxy_pass http://jellyfin:8096;
            proxy_set_header Host $host;
        }

        location /web/configurationpage {
            if ($arg_name = "Template") {
                rewrite ^ /template-html last;
            }
            if ($arg_name = "TemplateVueJS") {
                rewrite ^ /template-test-html last;
            }
            if ($arg_name = "configPageVueJS.js") {
                rewrite ^ /template-vuejs-js last;
            }
            if ($arg_name = "Template.js") {
                rewrite ^ /template-js last;
            }
            proxy_pass http://jellyfin:8096;
        }

        location = /template-html {
            alias /app/configPage.html;
            default_type text/html;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location = /template-test-html {
            alias /app/configPageVueJS.html;
            default_type text/html;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location = /template-vuejs-js {
            alias /app/configPageVueJS.js;
            default_type application/javascript;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location = /template-js {
            alias /app/configPage.js;
            default_type application/javascript;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location = /index_preview.html {
            alias /app/index_preview.html;
            default_type text/html;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location = /configPageVueJS.js {
            alias /app/configPageVueJS.js;
            default_type application/javascript;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }
    }
}
